authors:
  Lilon:
    name: Lise
    description: Creator
    avatar: https://media.licdn.com/dms/image/v2/D4D03AQFBlZhB4QRU5w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1705833047715?e=1735776000&v=beta&t=cYNCsX2eDrVsZMLCV1l7p3qYTRvsprXRE9KYsH-rhKQ
    url: https://www.linkedin.com/in/lise--pouchelon/
