version: '3'

services:
  mkdocs:
    build:
      context: ..
      dockerfile: docker/Dockerfile-env
    ports:
      - "8005:8000"
    volumes:
      - ../:/docs
    stdin_open: true
    tty: true
    command: serve -f config/fr/mkdocs.yml --dev-addr=0.0.0.0:8000
