INHERIT: ../mkdocs.yml

################ Project information ################
docs_dir: '../../docs/zh/'
site_dir: '../../generated/zh/'
site_description: >-
  Technical Margins 是一個探索技術寫作邊緣的空間。針對技術寫作者和好奇的讀者，這個部落格深入文件的隱藏層面、隨機思考，以及傳遞多元資訊的藝術。

################ Language configuration ################
theme:
  language: zh-TW

plugins:
  - blog
  - search:                                         
      lang: zh-TW

################ Analytics feedback localisation ################
extra:
  analytics: 
    feedback:
      title: 您怎麼想？
      ratings:
        - icon: material/thumb-up-outline
          name: 這篇文給了我靈感
          data: 1
          note: >-
            感謝您的回饋
        - icon: material/thumb-down-outline
          name: 我持不同觀點
          data: 0
          note: >- 
            感謝您的回饋

################ Nagivation ################
nav:
  - 首頁:
    - index.md
  - 部落格 :
    - blog/index.md
  - 關於我:
    - about/index.md