INHERIT: ../mkdocs.yml

################ Project information ################
docs_dir: '../../docs/en/'
site_dir: '../../generated/en/'
site_description: >-
  Technical Margins is a space for exploring the overlooked edges of technical writing. For technical writers and curious minds, this blog dives into the hidden layers of documentation, random reflections, and the art of sharing diverse information.

################ Language configuration ################
theme:
  language: en

plugins:
  - blog
  - search:                                         
      lang: en 

################ Nagivation ################
nav:
  - Home:
    - index.md
  - Blog:
    - blog/index.md
  - About:
    - about/index.md