name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-glightbox mkdocs-macros-plugin     
      - run: |
          # First build all sites
          mkdocs build --config-file config/fr/mkdocs.yml
          mkdocs build --config-file config/en/mkdocs.yml
          mkdocs build --config-file config/zh/mkdocs.yml
          
          # Copy global files
          sudo cp docs/index.html generated/
          sudo cp docs/404.html generated/
          
          # Prepare gh-pages branch
          git fetch origin gh-pages || true
          git checkout -B gh-pages
          
          # Remove existing content and copy the new generated files
          rm -rf *
          cp -r generated/* .
          
          git add .
          git commit -m "Deploy documentation"
          git push -f origin gh-pages