name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          
      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-glightbox mkdocs-macros-plugin
          pip install mike
          
      - name: Build FR docs
        run: mkdocs build --config-file=config/fr/mkdocs.yml
        
      - name: Build EN docs
        run: mkdocs build --config-file=config/en/mkdocs.yml
        
      - name: Build ZH docs
        run: mkdocs build --config-file=config/zh/mkdocs.yml
        
      - name: Copy redirect index page
        run: cp docs/index.html site/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
