name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build FR docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=config/fr/mkdocs.yml
      - name: Build EN docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=config/en/mkdocs.yml
      - name: Build ZH docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=config/zh/mkdocs.yml 

      - name: Copy redirect index page
        run: sudo cp /docs/index.html /generated

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated

      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-glightbox mkdocs-macros-plugin
      - run: pip install mike --force-reinstall --verbose
#      - run: mike deploy --push --update-aliases 1.0 latest --ignore
#      - run: mkdocs gh-deploy --force